--- 
default: 
  adapter: postgresql
  encoding: unicode
  host: localhost
  password: 12345
  username: postgres
development: 
  adapter: postgresql
  database: db/development
  encoding: unicode
  host: localhost
  password: 12345
  username: postgres
production: 
  adapter: postgresql
  database: db/production
  encoding: unicode
  host: localhost
  password: 12345
  username: postgres
test: 
  adapter: postgresql
  database: db/test
  encoding: unicode
  host: localhost
  password: 12345
  username: postgres
